// SquadPay's voice — written by Vedant 🇮🇳
export const LINES = {
  expenseAdded: [
    'Bhai ne fir se squad ko sponsor kar diya 💀',
    'Paise ek ne diye, maze sabne liye 😭',
    'Kharcha register ho gaya, bahane mat register karna.',
    'Bill aa gaya hai, ab acting mat karna.',
    'Squad outing successful, wallet unsuccessful.',
    'Khaana sabne khaya, UPI ek ne khola.',
    'Aaj ka sponsor mil gaya 🎉',
    'Ye expense future ke jhagde bachayega 😎',
    'Screenshot le liya gaya hai bhai 👀',
    'Paise gaye, yaadein reh gayi.',
  ],
  pending: [
    'Dosti apni jagah, ₹ apni jagah 😏',
    'Reminder: Udhaar amar nahi hota.',
    'Bhai payment kar de, izzat bach jayegi.',
    'Tera balance dekh ke calculator bhi ro raha hai.',
    'UPI ka button tujhe yaad kar raha hai.',
    'Squad ko tera intezaar hai 💸',
    'Debt level: Thoda suspicious.',
    'Abhi bhi pending? Kya EMI pe dosti chal rahi hai?',
    'Ye notification ignore karne se debt nahi jayega 😭',
    'Bhai, paise hawa mein nahi udte.',
    'Bhai payment kar de, screenshot ready hai 👀',
    'Debt level: Final Boss 💀',
    'Bro is treating debt like a family heirloom.',
    'Squad still believes in you.',
    'Wallet missing. Responsibility detected.',
  ],
  settled: [
    'Wah bhai, imaandari zinda hai 🎊',
    'Karz mukt jeevan mubarak ho.',
    'Friendship restored successfully 🤝',
    'Squad ne tujhe maaf kiya 😌',
    'Settlement complete, drama cancelled.',
    'UPI ne aaj apna farz nibha diya.',
    'Debt gaya, sukoon aaya.',
    'Ab tu officially tension-free hai.',
    'Paise pahunch gaye, duaayein bhi.',
    'Squad treasury updated 💚',
    'Debt has left the chat 🎉',
    'Achievement Unlocked: Responsible Adult',
    'Wallets are healing ❤️',
    'Economic crisis avoided 💀',
  ],
  funStats: [
    'Wallet ka sabse bada dushman: Squad.',
    "Most dangerous phrase: 'Main pay kar deta hu.'",
    'Squad ka favourite hobby: Kharcha.',
    'Savings ko aaj bhi intezaar hai.',
    'UPI apps are proud of this squad.',
    'Financial discipline not found.',
    'Sabse mehenga decision: Last outing.',
    'This squad treats budgets as optional.',
    'Savings account wants to meet you.',
  ],
  heroLines: [
    'Kharchon ka hisaab, dosti ka nahi.',
    'Bill split karo, friendship nahi.',
    'Track the bills. Keep the vibes.',
    'Built for squads. Feared by debtors.',
    '"Bhai baad mein bhejta hu" needs proof.',
    'The unofficial bank of every friend group.',
    'Squad ka finance department.',
    'Paise clear. Dosti stronger.',
    'Udhaar kam, maza zyada.',
  ],
  loading: [
    'Squad ko assemble kar rahe hain...',
    'Receipts count ho rahe hain...',
    'Wallets scan ho rahe hain...',
    'Debt detector active...',
    'Pizza statistics calculate ho rahi hain...',
    'Chaos loading...',
    'Friendship analytics incoming...',
  ],
};

export const pick = <T,>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)];
